archful = false
description = "This is package 'findpython' generated automatically by pyp2spec."
summary = "A utility to find python versions on your system"
version = "0.6.3"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "findpython"
python_name = "python-findpython"
url = "https://github.com/frostming/findpython"
source = "%{pypi_source findpython}"
archive_name = "findpython"
extras = []
