archful = true
description = "This is package 'pynacl' generated automatically by pyp2spec."
summary = "Python binding to the Networking and Cryptography (NaCl) library"
version = "1.5.0"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "pynacl"
python_name = "python-pynacl"
url = "https://github.com/pyca/pynacl/"
source = "%{pypi_source PyNaCl}"
archive_name = "PyNaCl"
extras = []
