archful = true
description = "This is package 'gssapi' generated automatically by pyp2spec."
summary = "Python GSSAPI Wrapper"
version = "1.9.0"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "gssapi"
python_name = "python-gssapi"
url = "https://github.com/pythongssapi/python-gssapi"
source = "%{pypi_source gssapi}"
archive_name = "gssapi"
extras = []
