archful = false
description = "This is package 'python-gvm' generated automatically by pyp2spec."
summary = "Library to communicate with remote servers over GMP or OSP"
version = "26.2.0"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "python-gvm"
python_name = "python-gvm"
url = "https://github.com/greenbone/python-gvm/"
source = "%{pypi_source python_gvm}"
archive_name = "python_gvm"
extras = []
